// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHHJlvuEZSjPlvsenEG1-OC5MlqHKNZKo',
    appId: '1:370634426641:web:5a92d48f2724270e0fe4b0',
    messagingSenderId: '370634426641',
    projectId: 'commv-cae28',
    authDomain: 'commv-cae28.firebaseapp.com',
    storageBucket: 'commv-cae28.firebasestorage.app',
    measurementId: 'G-RDQN8CVBYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY57K6a7apeutEK4bAjwcKRvp3FxK1U9E',
    appId: '1:370634426641:android:a53d54375cbbdcb90fe4b0',
    messagingSenderId: '370634426641',
    projectId: 'commv-cae28',
    storageBucket: 'commv-cae28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb3GhiqIKjJm58bic3gN70MCWtTTmk4UI',
    appId: '1:370634426641:ios:30bbda027359da300fe4b0',
    messagingSenderId: '370634426641',
    projectId: 'commv-cae28',
    storageBucket: 'commv-cae28.firebasestorage.app',
    iosBundleId: 'com.commv.commv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb3GhiqIKjJm58bic3gN70MCWtTTmk4UI',
    appId: '1:370634426641:ios:30bbda027359da300fe4b0',
    messagingSenderId: '370634426641',
    projectId: 'commv-cae28',
    storageBucket: 'commv-cae28.firebasestorage.app',
    iosBundleId: 'com.commv.commv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHHJlvuEZSjPlvsenEG1-OC5MlqHKNZKo',
    appId: '1:370634426641:web:3bf15ab3f994135e0fe4b0',
    messagingSenderId: '370634426641',
    projectId: 'commv-cae28',
    authDomain: 'commv-cae28.firebaseapp.com',
    storageBucket: 'commv-cae28.firebasestorage.app',
    measurementId: 'G-016H0P99HF',
  );
}
